version: '3.8'
services:
  postgres:
    container_name: postgres_db
    image: postgres:alpine
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASS
      POSTGRES_DB: sondb
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    networks:
      - docknet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: gabyta.inf@gmail.com
    ports:
      - 8080:80
    networks: 
      - docknet

  sonarqube:
    image: sonarqube:9-community
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_USERNAME: $PG_USER
      SONAR_JDBC_PASSWORD: $PG_PASS
      SONAR_JDBC_URL: jdbc:postgresql://postgres/postgres
    restart: always
    ports:
      - 9000:9000
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs      
    networks: 
      - docknet

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - 8099:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    networks: 
      - docknet
  
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    ports:
      - 8088:8081
    volumes:
      - nexus-data:/nexus-data
    networks: 
      - docknet

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - 9001:9000
    networks: 
      - docknet

  nodeapi:
    image: 'monikapaza/nodeapi:monica.apaza'
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - 3000:3000
    networks:
      - docknet

networks:
  docknet:

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_conf:
  jenkins_home:
  nexus-data:
  portainer-data: